apiVersion: v2
name: todo-app
description: A Helm chart for deploying the Todo Evolution application with Dapr and event-driven architecture to Oracle Cloud
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    alias: postgresql
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    alias: redis