apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.authSecret }}
  auth-secret: {{ .Values.secrets.authSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.cohereApiKey }}
  cohere-api-key: {{ .Values.secrets.cohereApiKey | b64enc | quote }}
  {{- end }}