apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: redpanda
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: docker.redpanda.com/redpandadata/redpanda:v23.2.13
        ports:
        - containerPort: 9092
          name: kafka-api
        - containerPort: 9644
          name: admin-api
        command:
        - /bin/sh
        - -c
        args:
        - |
          rpk redpanda start \
          --node-id 0 \
          --kafka-addr 0.0.0.0:9092 \
          --advertise-kafka-addr redpanda:9092 \
          --rpc-addr 0.0.0.0:33145 \
          --advertise-rpc-addr redpanda:33145 \
          --smp 1 \
          --memory 1G \
          --reserve-memory 0.2G \
          --overprovisioned \
          --set redpanda.auto_create_topics_enabled=true \
          --set redpanda.enable_transactions=true \
          --set redpanda.enable_idempotence=true
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  selector:
    app: redpanda
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
    name: kafka-api
  - protocol: TCP
    port: 9644
    targetPort: 9644
    name: admin-api
  type: ClusterIP