apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: task-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  # Redis/Valkey server configuration
  - name: redisHost
    value: "valkey:6379"  # This will be the service name in Kubernetes
  - name: redisPassword
    secretKeyRef:
      name: valkey-password
      key: password
  - name: actorStateStore
    value: "true"
auth:
  secretStore: kubernetes